# 1. El nombre del workflow es grupo6
name: grupo6

# 2. Se activa por push en la rama principal o por botón 
on:
  push:
    branches:
      - main
  workflow_dispatch:

# 3. Las tres variables de entorno personalizadas
env:
  VARIABLE1: "valor1"
  VARIABLE2: "valor2"
  VARIABLE3: "valor3"
  VARIABLE4: "valor4"


# 4. Trabajos y pasos de ejecución
jobs:
  ejecucion_grupo6:
    runs-on: ubuntu-latest
    steps:
      # Paso 1: Saludo al grupo
      - name: Prueba de mensajes
        run: |
          echo "¡Hola Grupo 6! Es la presentacion final del informe!."

      # Paso 2: Mostrar variables personalizadas
      - name: Variables creada en el workflow
        run: |
          echo "La primera variable contiene: ${{ env.VARIABLE1 }}"
          echo "La segunda variable contiene: ${{ env.VARIABLE2 }}"
          echo "La tercera variable contiene: ${{ env.VERSION }}"

      # Paso 3: Nombre solicitado con las 3 variables de GitHub Actions
      - name: Variables del entorno del Github Actions
        run: |
          echo "1. Nombre del repositorio: $GITHUB_REPOSITORY"
          echo "2. Dueño del repositorio: ${{ github.repository_owner }}"
          echo "3. Rama del repositorio: $GITHUB_REF_NAME"

          echo "Variable 1 de la web: ${{ vars.VARIABLE_WEB_1 }}"
          echo "Variable 2 de la web: ${{ vars.VARIABLE_WEB_2 }}"
          echo "Variable 3 de la web: ${{ vars.VARIABLE_WEB_3 }}"

      # Paso 4: Condicional Verdadera (Se va a ejecutar)
      - name: Con Despedida
        if: ${{ env.MOSTRAR_DESPEDIDA == 'true' }}
        run: |
          echo "¡Hasta luego, Grupo 6! Nos vemos en el siguiente ciclo."

      # Paso 5: Condicional Falsa (No se va a ejecutar)
      - name: Sin despedida
        if: ${{ env.MOSTRAR_DESPEDIDA == 'false' }}
        run: |
          echo "Este mensaje no saldrá en la consola porque la condición es falsa."
