# 1. El nombre del workflow es grupo6
name: grupo6

# 2. Se activa por push en la rama principal o por botón 
on:
  push:
    branches:
      - main
  workflow_dispatch:

# 3. Las tres variables de entorno personalizadas
env:
  VARIABLE1: "valor1"
  VARIABLE2: "valor2"
  VARIABLE3: "valor3"

# 4. Trabajos y pasos de ejecución
jobs:
  ejecucion_grupo6:
    runs-on: ubuntu-latest
    steps:
      - name: Prueba de mensajes
        run: |
          echo "¡Hola Grupo 6! Bienvenidos a la ejecución automatizada de GitHub Actions."

      - name: Variables creada en el workflow
        run: |
          echo "La primera variable contiene: ${{ env.VARIABLE1 }}"
          echo "La segunda variable contiene: ${{ env.VARIABLE2 }}"
          echo "La tercera variable contiene: ${{ env.VARIABLE3 }}"

      # Nuevo paso: Mostrando las variables por defecto de GitHub
      - name: Mostrar variables del repositorio de GitHub
        run: |
          echo "1. Nombre completo del repositorio: $GITHUB_REPOSITORY"
          echo "2. Dueño del repositorio: ${{ github.repository_owner }}"
          echo "3. Rama que originó el evento: $GITHUB_REF_NAME"
